### ISSUE TITLE
fiberassign's installation procedure assumes that install directory already exists.

### ISSUE THREAD

**Issue by weaverba137** [desihub/fiberassign#103]
It used to be the case that desiInstall would copy the entire contents of a downloaded package to a directory called `INSTALL_DIR`.  This has the side-effect of creating the directories that the fiberassign executables need to be copied to.  And the fiberassign `make install` process blindly assumes that these directories already exist.

The `make install` process should create the directories it is installing to, rather than making any assumptions at all about the install target.

**Comment by weaverba137** [comment]
Huh, the desiInstall procedure also does not set the `PLATFORM` variable (because that is a peculiarity of fiberassign), so presumably the generic platform is selected.

**Comment by tskisner** [comment]
Just as a point of reference, when I install fiberassign for dev installs (with some custom scripts I have), I use harpconfig to get the compile flags for the system (these are the same flags used to build specex).  I then copy the fiberassign python tools into the correct site-packages directory and run compileall.compile_dir() to ensure that all the pyc files are created on the filesystem.  This is needed since the global software location is read-only on the compute nodes, so we have to pre-compile things.

**Comment by weaverba137** [comment]
Hmm, it would be nice to actually use harpconfig at least.  That did remind me to update the individual platform files for cori and edison at least.
