### ISSUE TITLE
Optional config file

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#108]
PR #105 replaced the config ("features") file with command line options.  Although this is convenient for many cases, it could also be useful to have an optional config file to override the now-hardcoded numbers in `Feat::Feat()` or to specify the mtl, sky, outdir, etc. in a single location that could be archived along with the output tile files.

To do:
* Add an *optional* `--config` config file that could specify any of the parameters on the command line as well as any of the `Feat::Feat()` parameters.  If an option is specified in both the config file and the command line, the command line wins.
* Document what the numbers are in `Feat::Feat()`, including units
* Include an example config file in this repo.

**Comment by tskisner** [comment]
We can just pass an input file to the python layer argparse.  It is a trivial format with one string per line.

**Comment by tskisner** [comment]
I believe that the command line arguments of the new fba_* top-level scripts are sufficient to specify everything (along with the possibility of passing argparse options from a separate file, which is built in).  If we still desire a "config" file format, I would suggest TOML:

https://github.com/toml-lang/toml/wiki
https://github.com/toml-lang/toml

Which is simpler than YAML while maintaining nice features (like comments).  We should revisit this after integrating more hardware information / parameters, which may increase the number of options needed (and thus the need for a config file).

I'll leave this ticket open as a reminder for the future, but the scope has changed a bit in the time since the issue was opened.

**Comment by tskisner** [comment]
This issue is no longer relevant.  Closing.
