### ISSUE TITLE
sky fiber uniformity on focal plane

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#151]
From [DESI-4407](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=4407&version=1), the distribution of sky fibers on a particular tile is very non-uniform:
![image](https://user-images.githubusercontent.com/218471/47946139-d1d2a780-dec4-11e8-93d4-1c41368b820e.png)

I suspect that fiberassign is assigning sky fibers in the order of fiber number and then stopping when it reaches its number goal, resulting in clumps of sky fibers on the focal plane (and on the CCD).  This could be verified by stacking a large number of different tiles, or by histogramming how often each fiber is assigned to a sky location, but I don't have a large set of tiles available right now.  This may also be an artifact of how the real-data sky locations are selected.

To be clear: we want the sky fibers to be distributed across the focal plane and across the CCD.  The requirement of 40 fibers per petal may not be strict enough to get the uniformity we want.

@forero could you check this with the assignments you generated for DESI-4407, and point us to where those files are?

@forero @rncahn @tskisner can you confirm how the code choses which order it assigns sky targets to fibers?

**Comment by forero** [comment]
I am testing that right now.

**Comment by forero** [comment]
Just for comparison, here is the plot for std fibers in 500 tiles (selected because they used 100 std fibers)

![download-2](https://user-images.githubusercontent.com/1848618/47956595-c76fe680-df74-11e8-98f0-58377054adef.png)

**Comment by tskisner** [comment]
I will comment more tonight or tomorrow, but briefly:  the existing code does the sky and standard assignment in fiber ID order, rather than priority order like the science targets.  The new code assigns all three types (science, standard, sky) in priority order.  I have a temporary hack in place just to compare to the old code.  So, in the new scheme, you could influence the distribution within a petal by assigning the sub priority values accordingly.

I am working hard to tie up some loose ends, including the output writing, so that the new code can get more testing.  I can send updates to this ticket over the next couple days.

**Comment by rncahn** [comment]
I am a bit surprised by this.  The sky fibers and standard stars are the
last things done and so primarily go in the unassigned locations.  I would
have thought that would dominate the distribution except in petals with
many unassigned fibers.  Moreover, aren't we now filling all unassigned
fibers with sky fibers?

**Comment by sbailey** [comment]
Assuming that the fix is a bit messy, we should fix this in Ted's refactor after he has confirmed that he can reproduce the existing code, and not a fix in the existing code that will further conflict with Ted's updated code.

I agree with @rncahn's confusion about why this is so pronounced given that we are supposed to be filling in with sky fibers anyway, and any bumping should be in order of target priority not fiber number.  To make matters even more subtle, the hotspots on Jaime's plots correspond to fibers around 300-350, not fibers 0-50.  I reattach Jaime's plot followed by a scatter plot of positioner locations color coded by FIBER%500 for comparison:

![download-1](https://user-images.githubusercontent.com/1848618/47956573-84ae0e80-df74-11e8-840b-4204ad82fbdf.png)
![xy](https://user-images.githubusercontent.com/218471/48029599-6cb8c500-e103-11e8-9e49-e8321bfb559c.png)

**Comment by tskisner** [comment]
Just wanted to add more comments to this thread.

1. In the current master version, the assignment of unused fibers to science targets occurs in order of fiber priority (determined by max priority of targets available to each fiber):
https://github.com/desihub/fiberassign/blob/master/src/global.cpp#L419
However, when assigning standards or skies to unused fibers, the fibers within a petal are looped over in fiber order:
https://github.com/desihub/fiberassign/blob/master/src/global.cpp#L655

2.  In the new version, I use the same code to assign unused fibers to all 3 object types, and assign fibers in priority order in all cases.

3.  In the master version, I believe there is a bug.  When bumping science targets, the objects to be bumped for a given target class are chosen based on the *lowest* priority (which makes sense):
https://github.com/desihub/fiberassign/blob/master/src/global.cpp#L465
However, that same sorting function is used when assigning standards and skies to unused fibers:
https://github.com/desihub/fiberassign/blob/master/src/global.cpp#L662

So this means that in the master version the standards (and skies) are being assigned in reverse priority order to unused fibers.  I fixed this bug in my local copy of master, and am working on hacking a change to point number one above to agree with my version.

I'm also making progress on the writing of data in my branch, so that I can replace the fiberassign main program and hand it off to more people for testing.

**Comment by sbailey** [comment]
@forero could you re-check this using your latest fiberassign run on DR8?  I don't think we ever figured out what was causing it, but it would be helpful to re-verify if it is still a problem.

**Comment by forero** [comment]
@sbailey @tskisner 

Here is the new pattern
![Screen Shot 2019-07-22 at 3 40 01 PM](https://user-images.githubusercontent.com/1848618/61636964-0080f000-ac97-11e9-87c9-b3d3768d3e75.png)
![Screen Shot 2019-07-22 at 3 40 05 PM](https://user-images.githubusercontent.com/1848618/61636976-037be080-ac97-11e9-8ffc-2ca829ea5d70.png)

it's similar for both sky and standards, but it's not clear to me why it is the way it is.

**Comment by djschlegel** [comment]
Is this the new (Eddie's) tiling pattern?  This may reflect that given the overlaps preferentially on the outer part of the focal plane, given the tiling pattern, there are fewer opportunities to observe science targets with an inner fiber, so they're less often used for standards.  You might want to plot all the fiber potential assignments, and see if it looks the same as the above?

**Comment by forero** [comment]
The tiling comes from whatever is now the default in `desimodel`. I am not sure whether this is the new one or not.

**Comment by tskisner** [comment]
As of #258, assignments and bumping are done based on target total priority order, not based on any fiber or location ordering.  I assume this will resolve any imprinting mentioned in this issue.  Leaving open until some kind of final confirmation, but I believe this is resolved.

**Comment by forero** [comment]
Here are the new results. This is again for DR8 data.

![SKY_pattern](https://user-images.githubusercontent.com/1848618/77720544-37da3600-6fb6-11ea-8f66-1f52d18147c8.jpg)

![STANDARD_pattern](https://user-images.githubusercontent.com/1848618/77720555-3d378080-6fb6-11ea-82eb-100294d7e522.jpg)

I am not sure what might be happening with the sky fibers. I used `--rundate 2020-01-01T00:00:00` for `fba_run`. Not sure if that might have an impact.

**Comment by tskisner** [comment]
@forero, can you point me to the input files you used and the commands / script / notebook?

If this was run at NERSC, can you tell me which version of the desi stack you had loaded?

When making these plots, are you just plotting the X/Y of assigned targets across all tiles on the same plot?  And so darker regions are areas in X/Y space that received many assignments?

Petal locations 1 and 2 seem to have patterns associated with the positioner angle range.  Anyway, hopefully we can sort this out quickly.

**Comment by forero** [comment]
@tskisner This was run on nersc sourcing `desi_environment master`
 
Typing `which fba_run` returns `/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/bin/fba_run`

This is the command I used
`fba_run --targets targets/dark_gray_north.fits --sky targets/sky_north.fits  --footprint footprint/tiles_dark_gray_north.fits --rundate 2020-01-01T00:00:00 --dir fba_dark_gray_north --overwrite`

from this location

`/global/cscratch1/sd/forero/SandboxDESI/DR8/targets`

When making the plots I simply plot X/Y of the assigned sky targets. Darker regions means that there were many assignments.

However, here are the plots when I run with a date of `2019-01-01T00:00:00`

![SKY_pattern (1)](https://user-images.githubusercontent.com/1848618/78086331-39737780-7383-11ea-98fb-fceee9fb209b.jpg)
![STANDARD_pattern (1)](https://user-images.githubusercontent.com/1848618/78086346-42fcdf80-7383-11ea-9e30-c3862a031b77.jpg)

![STANDARD_pattern (1)](https://user-images.githubusercontent.com/1848618/78086339-3e382b80-7383-11ea-8be2-ded3987cabee.jpg)

That looks much better.

**Comment by forero** [comment]
And this is the notebook I used to prepare the plots https://github.com/forero/SandboxDESI/blob/master/fiber/sky_pattern.ipynb

**Comment by forero** [comment]
@tskisner What do you think is the reason for the small black circular spots?

**Comment by tskisner** [comment]
Thanks for the additional info @forero, I'll be working on fiberassign again (including this issue) starting Friday.

**Comment by tskisner** [comment]
At least some of the problems listed in this issue were fixed in #267. It's not clear to me if there are remaining issues here.  I guess we should see if anything changes with current versions of desimodel and fiberassign.

**Comment by dstndstn** [comment]
FIxed (#338 and other previous improvements)

**Comment by tskisner** [comment]
So much has changed that I think we should close this now and open a new issue if there are additional problems.
