### ISSUE TITLE
SKY vs. BAD_SKY

### ISSUE THREAD

**Issue by forero** [desihub/fiberassign#152]
The current implementation of `fiberasign` considers as sky fibers all the targets passed in the `sky.fits` file. A new implementation needs to give higher priority to `SKY` locations over `BAD_SKY`.

**Comment by sbailey** [comment]
`BAD_SKY` targets shouldn't be included in the `sky.fits` file in the first place.  They should be included in the targets / MTL as low-priority targets of last resort.  i.e. I don't think this should require any changes to fiberassign itself, but rather it should be a change to how the `sky.fits` file is generated.

Mentioning @geordie666 for his comments.  e.g. are bad skies identified in the same piece of code as normal skies, and thus it is a technical challenge to put them back into the normal targets.fits file?  I haven't found a DR7 skies file to look.

**Comment by forero** [comment]
@sbailey This is the DR7 sky file I've been using `/project/projectdirs/desi/target/catalogs/dr7.1/0.22.0/skies-dr7.1-0.22.0.fits`

**Comment by geordie666** [comment]
`SKY` and `BAD_SKY` targets are both generated by the same piece of code (with `BAD_SKY` simply being set as locations that exceed some measured flux threshold in the imaging surveys).

This means that removing the `BAD_SKY` locations from the `skies` file would require an after-burner on target selection, or a pre-burner on fiber assign. I'm not sure which choice would be more efficient.

**Comment by sbailey** [comment]
@forero for the purposes of closeout documentation, could you generate a custom skies file that has pre-removed the BAD_SKY targets, and then rerun?  Even better if you re-add those BAD_SKY locations to a custom MTL file and re-run.  Either way, by-hand-hacks for now for checking statistics, not automated code.

Longer term this will be easier to handle after Ted's refactor is ready, since the shuffling can happen within the python I/O code before passing the targets and sky arrays to C++.

**Comment by tskisner** [comment]
This issue is no longer relevant.  Fiberassign now has a concept of targets of last resort (the "SAFE" target type).  BAD_SKY is used for this by default and that behaviour can be fully controlled by customizing bitmasks at the commandline or high-level API.
