### ISSUE TITLE
Treat BAD_SKY as a unique target type

### ISSUE THREAD

**Issue by tskisner** [desihub/fiberassign#175]
This ticket attempts to capture discussion on recent telecons an offline conversations.  Currently fiberassign (both the legacy and new code) treats BAD_SKY targets as low-priority science targets.  Instead, I propose to treat these targets as separate from science, standards, and sky.  There is actually already a fourth target type built in to fiberassign called "safe" targets.  This target type was intended to simply be a safe place to put an unassigned fiber as a last resort.

Specifically, the proposed behavior is:

1.  When loading targets from a file, any target with BAD_SKY set in DESI_TARGET would by default be assigned the internal fiberassign type TARGET_TYPE_SAFE instead of TARGET_TYPE_SCIENCE.

2.  In the top-level main script, this target type would not be used until the very end, and then a single call to ```assign_unused(TARGET_TYPE_SAFE)``` would be made.  This line is actually already in the code and just needs to be uncommented.

The main consequence of this change is that there would likely be more "regular" sky targets assigned and fewer bad_sky targets.

After this is done, we should also close #152 .

**Comment by sbailey** [comment]
+1

Fleshing out this comment a little more since I was the one who originally requested that BAD_SKY be treated just as ultra low priority science targets, but then in discussions with @tskisner and @kdawson1000 I keep re-discovering that this is a bad idea and then forgetting why:

> The main consequence of this change is that there would likely be more "regular" sky targets assigned and fewer bad_sky targets.

Currently BAD_SKY are just ultra-low priority science targets, which means that they get used as filler targets *before* using SKY as filler targets.  We'd rather use SCIENCE, STD, and SKY first, and then BAD_SKY as the last type of filler target.

i.e. our order of assignment should be:

1. science targets with numobs_more>0
2. stdstars on unused fibers up to some density limit (default 10/petal)
3. sky on unused fibers up to some density limit (default 40/petal)
4. if needed, bump low priority science to achieve minimum stdstar density
5. if needed, bump low priority science to achieve minimum sky density
6. assign science to any unused fibers (I think this is a no-op due since they should have been placed in step (1) anyway
7. assign std to any unused fibers (possibly exceeding original minimum stdstar density)
8. assign sky to any unused fibers (possibly exceeding original minimum sky density)
9. assign BAD_SKY to any unused fibers

At this point there should not be any unassigned fibers left, or otherwise we need to go back to target selection and get more SKY/BAD_SKY targets at the unassigned locations.

Note: currently BAD_SKY is our only SAFE target bit, but in general we might have other bits in the same category in the future.  This concept is encoded in `fiberassign.targets.get_safemask`.

**Comment by kdawson1000** [comment]
Stephen's proposal looks correct to me.
