### ISSUE TITLE
 SUPP_SKY to only be assigned if there is no SKY available

### ISSUE THREAD

**Issue by Srheft** [desihub/fiberassign#212]
@tskisner, @sbailey :

Trivia: desitarget has released a sky supplement catalog(empty sky locations with no measured flux and with [separate bit than SKY](https://github.com/desihub/desitarget/blob/8c8ee3010d3b82859096456349a12a06ed17dbca/py/desitarget/cmx/data/cmx_targetmask.yaml#L25)). This is to help with tiles that lie at the edges of footprint and whereever there is no chance that positioner can reach a SKY location.

The fiberassign algorithm, currently treats both SKY and SUPP_SKY the samewhich has caused unnecassary SUPP_SKY assignments for tiles that are [no where near the edges of the footprint](http://legacysurvey.org/viewer?ra=220&dec=0.0&layer=dr8&desifoot&desifiber&zoom=8) and in no need to use sky supplements. For example: the tile at RA=220.0, dec=0 gets 1850 SUPP_SKY assignments:

Tile 059492 RA: 220.8 DEC: 0.0
bit: 1   ['STD_GAIA'] 493
bit: 2   ['SV0_STD_FAINT'] 11
bit: 3   ['STD_GAIA', 'SV0_STD_FAINT'] 67
bit: 4   ['SV0_STD_BRIGHT'] 429
bit: 4294967296   ['SKY'] 2150
bit: 141733920768   ['SKY', 'SUPP_SKY'] 1850
Total CMX targets assigned: 5000
number of assigned targets with FLUX=-1.0 1850

 while if we run the fiberassign without [sky supplement catalog](https://portal.nersc.gov/project/desi/users/adamyers/forrongpu/0.32.0/skies/), tile gets a full assignment with SKY positions:

bit: 1   ['STD_GAIA'] 503
bit: 3   ['STD_GAIA', 'SV0_STD_FAINT'] 76
bit: 4   ['SV0_STD_BRIGHT'] 415
bit: 513   ['STD_GAIA', 'SV0_MWS'] 1
bit: 4294967296   ['SKY'] 4020
Total CMX targets assigned: 5015
number of assigned targets with FLUX=-1.0 0

The 1850 SUPP_SKY positions are uniformly distributed across the tile and not accumulated near a certain area [bad imaging near bright source in a petal, etc].

![image](https://user-images.githubusercontent.com/32471902/63968310-a6750680-ca5c-11e9-9d42-76ed030549cb.png)
 

This needs urgent attention as I have to redo bunch of data delivery items for the review panel in Tucson after the fx is in place. 

Let me know if you don't find this an issue; meaning that it is OK to not know the flux of 1850 of empty sky locations:

![image](https://user-images.githubusercontent.com/32471902/63968509-2ac78980-ca5d-11e9-8969-e1b9260d2e29.png)

**Comment by sbailey** [comment]
Thanks @Srheft.  This is absolutely a problem, but @tskisner is also currently tied up in some critical pipeline tasks before he can return to fiberassign, and there are also other fiberassign as-built hardware issues waiting for him.  Could you try to make the fiberassign fix to address this SUPP_SKY problem?

Another option would be to update desitarget so that in a given (large nside) pixel, it would generate only SKY or SUPP_SKY but not both.  This is less ideal since there would still be cases where one pixel would have SKY and a neighboring pixel would have SUPP_SKY but a fiber could overlap both and still have to chose.

mentioning @geordie666 to get him in the loop on the desitarget option.

**Comment by Srheft** [comment]
@sbailey :

`Could you try to make the fiberassign fix to address this SUPP_SKY problem?`

Sure, I'll see if I can find the proper place in the code and let you know if I successfully fixed this.

**Comment by Srheft** [comment]
FYI: My initial inclination was to give the same "last resort" role as BAD_SKY to SUPP_SKY  in safe_mask but this did not work out.

Stephen's comment:
`If SUPP_SKY is used as "last resort" targets, then they don't count towards the sky budget and anything else takes priority over them.  They are reasonable "last resort" options, but that is a bit different from what we want if we are starved for sky fibers and need to assign some SUPP_SKY.  If I recall correctly, internally fiberassign simplifies the N>>1 targeting bits into basic categories of SCIENCE, SKY, STANDARD, SAFE.  I think we'd need to add another category like SUPP_SKY and some if/then logic to assign SKY first, and then continue with SUPP_SKY only if needed.`

**Comment by tskisner** [comment]
Looking at the comment here:

https://github.com/desihub/desitarget/blob/master/py/desitarget/cmx/data/cmx_targetmask.yaml#L25

I think the problem is that SUPP_SKY targets also have the SKY bit set.  Instead, if these targets did NOT have the sky bit set, then we could filter them into the "safe" target category on read.

Are the SUPP_SKY targets somehow better than BAD_SKY?  If not, then I suggest:

1.  Do not set SKY bit for SUPP_SKY targets

2.  Modify the default "safe" bits for all survey types to include the SUPP_SKY bit:

https://github.com/desihub/fiberassign/blob/master/py/fiberassign/targets.py#L90
https://github.com/desihub/fiberassign/blob/master/py/fiberassign/targets.py#L145
https://github.com/desihub/fiberassign/blob/master/py/fiberassign/targets.py#L207

Now all "real" sky targets will be assigned first and then anything matching SUPP_SKY or BAD_SKY will be assigned as a last resort:

https://github.com/desihub/fiberassign/blob/master/py/fiberassign/scripts/assign.py#L364

If the SUPP_SKY targets are somehow "better than BAD_SKY" but "worse than SKY", then we could create a new class of target internally.  However, this kind of thing feels like splitting haris.  I feel it would be better to just count these targets as genuine sky or as last resort locations like BAD_SKY.

**Comment by geordie666** [comment]
@tskisner: As regards your point (1) I'll have to loop in @sbailey as he specifically requested that I *should* set the `SKY` bit every time `SUPP_SKY` was set.

**Comment by tskisner** [comment]
Ok, so I'm probably not understanding something.  The original "SKY" targets are locations determined to be free of flux from other sources, using the imaging data.  These SUPP_SKY targets are the same, but have been extrapolated off the footprint using GAIA data, correct?

Is there some reason we don't just use "traditional" sky targets within the footprint and "supplemental" sky targets off the footprint?  Then we could just call everything SKY.

**Comment by geordie666** [comment]
It would be my _strong_ preference to do exactly what you're proposing: Only use `SKY` locations within the footprint of the imaging surveys and use `SUPP_SKY` off that imaging footprint. But, I'm not sure the infrastructure exists (downstream of desitarget) to know when we are or are not on the Legacy Surveys imaging footprint? And, in particular, when we might be in a chip gap, etc.? Either way, I suspect @sbailey will want a different bit to codify the different processes for establishing a sky location.

**Comment by geordie666** [comment]
Oh, and to clarify: `SUPP_SKY` are less sophisticated than `SKY`. `SUPP_SKY` merely avoid Gaia sources by a 2 arcsecond radius. In that sense they should be inferior to `SKY` locations, which, as you say, extract flux in apertures at the locations of the actual pixels of the Legacy Surveys.

**Comment by tskisner** [comment]
Ok, it sounds like this could be accomplished by reading the SKY and SUPP_SKY catalogs, loading the desi footprint, and writing a new combined catalog that had SKY inside the footprint and SUPP_SKY outside the footprint.  Obviously that requires a bit of scripting.  Happy to do that after I make some progress on other fiberassign issues.  To me, this solution is much easier than adding a whole new type of object into fiberassign.  Either way, we should leave this issue open until the SUPP_SKY targets are handled properly.

**Comment by sbailey** [comment]
Clarifying (maybe):  SUPP_SKY should be used to fulfill the sky fiber budget if there aren't enough SKY fibers.  This is different from BAD_SKY, which are just bad and are not used for sky modeling.

Catalogs with "SKY on footprint and SUPP_SKY off the footprint" is good, but we also may want to fill in SUPP_SKY in chip gaps too.  I'm hoping that is a small effect but I don't know the quantitative numbers for it.

Even with that, we still need fiberassign to prefer SKY over SUPP_SKY.  For the tiles that hang off the edge of the footprint, we don't want it to completely fill its SKY budget by using SUPP_SKY locations off the edge where there aren't any primary science targets.

**Comment by Srheft** [comment]
Adding some numbers for Stephen's comment here:
`Catalogs with "SKY on footprint and SUPP_SKY off the footprint" is good, but we also may want to fill in SUPP_SKY in chip gaps too. I'm hoping that is a small effect but I don't know the quantitative numbers for it.`

When NOT using sky summplemt catalog and trying to assign all the fibers to SKY in MAIN survey tiles:
out of  [10043 dark tiles](http://www.astro.utah.edu/~u6022465/MAIN/MAIN_DARK.html) in main survey, 597 tiles are left unassigned. 
out of [6028 bright tiles](http://www.astro.utah.edu/~u6022465/MAIN/MAIN_BRIGHT.html) in main survey, 364 tiles are left unassigned.

As you can see in the plots, not all of the unassigned [red] tiles are in the edges of the footprint.  
I used the main survey tiles to assess the extent of the use of the sky supplement for the tiles that are fully within the footprint [in the tightest grid]. The list of the FULLY INSIDE the footprint tiles, that do need supplement, is available if it helps to quantify how many chip gaps we are dealing with.

**Comment by tskisner** [comment]
Summarizing offline discussion:  we do need to add a new type of target to fiberassign.  This is tedious but straightforward.

**Comment by tskisner** [comment]
Hi folks, this is now implemented in #241 .  However, because fiberassign now tries to assign "normal" sky first and then falls back to "supp sky", we must ensure that targets used internally to fiberassign are classified as one or the other (not both).  If a supp_sky target is also classified as a "sky", then it would just get assigned as a sky target in the first round.

I believe that current supp_sky target files have both the SKY and SUPP_SKY target bits set.  This means that "regular sky" targets cannot be differentiated from supp_sky without hacking in additional bitwise operations.  Currently targets are categorized with single bitwise-and of a mask.

@sbailey and @geordie666, must we really set the SKY bit for SUPP_SKY targets?

**Comment by geordie666** [comment]
@tkisner: I'm ambivalent to whether we set both `SKY` and `SUPP_SKY` for supplemental sky targets...I believe I did it this way simply because @sbailey requested it.

Although, I don't really see why it's critical to not set `SKY` for `SUPP_SKY`. Currently:

- sky targets have `SKY` set but not `SUPP_SKY` set.
- supplemental sky targets have 'SUPP_SKY` and `SKY` set.

Under (I think) your proposed formalism:

- sky targets would have `SKY` set but not `SUPP_SKY` set.
- supplemental sky targets would have 'SUPP_SKY` set but not `SKY` set.

I think either case is characterized by the bitwise operation 'SUPP_SKY' is (or is not) set. Again, though, I don't have a strong preference if one way is easier for you to code.

**Comment by tskisner** [comment]
Currently every target is classified into science, standard, sky, suppsky, and safe categories using a bitwise-and with a mask (the mask has a default value and may be overridden).

Although doing other bit-operations is trivial, it breaks the current model.  It forces us to do things like, "for this survey and this target class, do this custom bit operation".  It also means that we can't override this arbitrary bit-operation from the command line.

If this is really a requirement, then I guess we just hard-code the bits used for sky / suppsky across all surveys and disable overrides for those from the command line.

I'll wait for comment from @sbailey before proceeding.

**Comment by geordie666** [comment]
Note that it _is_ easy for me to change the bit-mask behavior, so @sbailey should weigh relatively little work for me against what seems to be more substantial work for @tskisner.

**Comment by sbailey** [comment]
I may be overriding previous comments from myself, but yea verily:

SKY and SUPP_SKY should be set as independent bits, and we should *not* set SKY just because SUPP_SKY is set.  This allows SKY to be interpreted by itself (it was selected based upon imaging data) and not have it mean different things depending upon whether or not SUPP_SKY was set.  I think this is what fiberassign needs (but that isn't the only motivation).

**Comment by tskisner** [comment]
OK, thanks for the clarification.  It sounds like that is an easy change for @geordie666 to make (i.e. not set SKY for SUPP_SKY targets).  As soon as that is in place, then #241 should produce the desired behavior (assigning SKY first and then falling back to SUPP_SKY to meet the per-petal sky budget).  I'm not sure if #241 would mess up runs by @Srheft before she has updated SUPP_SKY target files.  We can wait to merge that until the updated target files are ready.

**Comment by geordie666** [comment]
@tskisner: I'll make that change this week, but I have a couple of other changes I need to make to `desitarget`, too. Everything will likely propagate into new files by (or more likely over) next weekend.

**Comment by tskisner** [comment]
This is now fully implemented.
