### ISSUE TITLE
Problems with fibers not assigned to locations

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#220]
In the current desimodel trunk focalplane model, fibers 1497 and 3078 are not assigned to any positioners, while positioner locations 2261 and 6484 are assigned to FIBER=-1 even though the equivalent locations on other petals are assigned to fibers.

As a result, these two fibers do not appear in fiberassign output, and those positioner locations are assigned to FIBER>5000 numbers, intermingled with the ETC sky monitor fibers.

This is problematic for downstream code that has been assuming that every fiber is represented in the fibermap, even if it is broken.  It might also be a problem for ETC fiber bookkeeping.  Maybe.

I would prefer to fix this by associating LOCATION:FIBER 2261:1497 and 6484:3078, but we need to do that in a way that won't get undone the next time we get an update from the hardware folks.  e.g. can we get them to agree to that mapping and fix it upstream?

Otherwise we'll need a deep dive on FIBER assumptions throughout the code, or some other post-fiberassign hack.

Although the problem starts with the focal plane model files in DESIMODEL, I'm opening this ticket in fiberassign because that is the first place where it has an impact, causing it to write files that don't match our data model of requiring all fibers to be represented even if they are broken.

@tskisner @julienguy thoughts?

**Comment by tskisner** [comment]
A couple of notes / questions:

1.  There is the meta-question of how to propagate problems we find to the upstream instrument folks.  For example docdb 4807 still has that one slitblock / blockfiber typo, which I am manually fixing.  I don't know the best channel for communicating things so that they don't fall through the cracks.  The commissioning mailing list is a bit of a firehose, but maybe that is the best place.

2.  We are using the pos_settings svn, which the instrument folks have deprecated in favor of their database.  So I suppose they could always say, "use the database" if we raise an issue like this (assuming it was fixed there).

3.  This emphasizes the need to switch to that DB as soon as possible.

In the mean time, I suggest we maintain a clearly labelled section of hardcoded fixes like this, and then simultaneously push that information upstream.  I can work on doing that soon.

**Comment by sbailey** [comment]
> In the mean time, I suggest we maintain a clearly labelled section of hardcoded fixes like this, and then simultaneously push that information upstream. I can work on doing that soon.

Sounds good.  Thanks.

**Comment by tskisner** [comment]
I have already committed a fixed focalplane file to desimodel svn trunk.  This should fix any fiberassign problems.  Separately there is this PR https://github.com/desihub/desimodel/pull/118 which fixes the script that generates the focalplane file.

**Comment by tskisner** [comment]
This issue was in upstream desimodel and was fixed long ago in that package.
