### ISSUE TITLE
qa-fiberassign error log:  location map incorrect

### ISSUE THREAD

**Issue by Srheft** [desihub/fiberassign#229]
@sbailey, @tskisner 

Assuming no changes happened since PR#240 for this definition, fiber location is defined as LOCATION = 1000*PETAL_LOC + DEVICE_LOC 

qa-fiberassign [does check](https://github.com/desihub/fiberassign/blob/390eb4fa5e401e5fbcba55528ebe1ae518732262/bin/qa-fiberassign#L158) the [fibermap from the desimodel](https://github.com/desihub/fiberassign/blob/390eb4fa5e401e5fbcba55528ebe1ae518732262/bin/qa-fiberassign#L41) and the their indicators in the assignment output. 
I did attempt to update the definition but the new definition does not have a match in 
 fiberpos (`desimodel.io.load_fiberpos()`).

 fibermap keys
 [PETAL, DEVICE,DEVICE_TYPE, LOCATION,FIBER, X,Y, Z,Q,S,SPECTRO,SLIT,SLITBLOCK,BLOCKFIBER,POSITIONER,SPECTROGRAPH] 

FIBERASSIHGN HDU [FIBER, LOCATION,NUMTARGET,DESIGN_X, DESIGN_Y, DESIGN_Q,DESIGN_S,PETAL_LOC,DEVICE_LOC]

I am not able to match 1000*PETAL_LOC + DEVICE_LOC from fiberassign output with LOCATION in [desimodel fiberamp ](https://github.com/desihub/fiberassign/blob/390eb4fa5e401e5fbcba55528ebe1ae518732262/bin/qa-fiberassign#L39)or any other combo. Any ideas?  

FYI: the pushed branch qa_related_phase2 tries to address this.

**Comment by Srheft** [comment]
Just a quick note that I used the formats branch and stll get the same "location map incorrect" error. In fact, looking at all my previous runs of qa-fiberassign, I've always gotten this error. would be good to fix it before cmx run as it loks like a very good thing to check.

**Comment by tskisner** [comment]
The fiberassign switch to using location (which is fixed to the focalplane) rather than fiber ID happened in PR #204 on June 3, 2019.  The switch to the new desimodel focalplane happened on June 13, 2019 with this commit:

https://github.com/desihub/fiberassign/commit/9e7770b9d7c5731f020c9b75801eae752f47dd3c

I did not even realize that the "qa-fiberassign" executable was still being used (I thought it was leftover from the legacy code), but looking at the history it seems that @sbailey kept it up to date through some of those past changes.  However, it is still using the fiberpos file from desimodel, which is completely different from the focalplane model used throughout fiberassign.

**Comment by sbailey** [comment]
Yes, qa-fiberassign is still used and still useful.  I've opened desihub/desimodel#126 about the deprecation plan for fiberpos.fits.  In the meantime, this ticket can track the fix to update qa-fiberassign to use the new `desimodel.io.load_focalplane()`.

**Comment by Srheft** [comment]
Thanks for comments Ted and Stephen. I have added the dsimodel.io.load_focalplane() to qa_related_phase2 branch and am waiting for the formats branch to be merged into master to make this branch  a PR.

**Comment by Srheft** [comment]
[This table](https://docs.google.com/spreadsheets/d/1LOjXASgI9WNQ-LD4TZhBF-lwKOutfNMlosOW3_mhw2g/edit?usp=sharing)  lists (FIBER,LOCATION) of 'FIBERASSIGN' HDU and those of the focalplane model. The Location of two of the ETC fibers in focal plane model, matches those of the POS fibers in the fiberassign output. The example file is [here](http://www.astro.utah.edu/~u6022465/cmx/tiles/sandbox/Oct2019/newformat/tile-066000.fits):

`
fibermap = desimodel.io.load_focalplane()`
`fiberpos = fibermap[0]`
`fiberpos.sort('FIBER')`
`fiber_locations = sorted(zip(fiberpos['FIBER'], fiberpos['LOCATION']))`
`fa,h= fitsio.read('tile-066000.fits',ext=1,header=True)`
`floc= sorted(zip(fa['FIBER'], fa['LOCATION']))
`

comparing two lists above: fiber_locations and floc

**Comment by sbailey** [comment]
@Srheft I think this is a match.  In the desimodel focalplane files, the ETC positioners don't have a defined FIBER number and are assigned -1.  fiberassign renumbers those FIBER 5000-5019 but it looks like a bug that they are showing up as DEVICE_TYPE POS instead of their original ETC type.

There may be two fixes here:
* updating desimodel to have a well defined fiber number for the ETC fibers
* updating fiberassign to retain these as DEVICE_TYPE ETC

For the purposes of your QA, can you work around these mis-matches or otherwise ignore FIBER>=5000 for now?

**Comment by Srheft** [comment]
thanks @sbailey; I do have a work around that considers this a match by only matching the locations; I'll add that for now and it can be mold to perfection later on.
