### ISSUE TITLE
mix of KPNO and NERSC provenance in SV1 fiberassign files/headers

### ISSUE THREAD

**Issue by moustakas** [desihub/fiberassign#302]
Mildly related to https://github.com/desihub/desispec/issues/1076.

At least one (and probably several) SV1 fiberassign files/headers have KPNO provenance for the input catalogs, which breaks when these headers are used at NERSC for analysis, e.g.,
```
fahdr = fitsio.read_header('/global/cfs/cdirs/desi/target/fiberassign/tiles/trunk/{}/fiberassign-{}.fits.gz'
fahdr

[snip]
GFA     = '/data/target/catalogs/dr9/0.47.0/gfas' /
SKY     = '/data/target/catalogs/dr9/0.47.0/skies' /
SKYSUPP = '/data/target/catalogs/gaiadr2/0.47.0/skies-supp' /
TARG    = '/data/target/catalogs/dr9/0.47.0/targets/sv1/resolve/bright/' /
[snip]
```
The `TARG` header card, e.g., at NERSC would be `/global/cfs/cdirs/desi/target/catalogs/dr9/0.47.0/targets/sv1/resolve/bright/`.

**Comment by araichoor** [comment]
that is correct, that happens for the tiles I designed on Dec, 18th at KPNO when NERSC was down, i.e. for tiles 080611-080623.
I kept the KPNO path so that there is no ambiguity on where the origin of the target files: is it a problem? i.e. if I'll have to design tiles at KPNO in the future, is it ok if I continue to do that?
because a simple work-around is to use fahdr["TARG"].replace("/data/","/global/cfs/cdirs/desi/").

**Comment by araichoor** [comment]
in case it s useful for your analysis: for each tile, for SV at least, I currently keep the input files used when running the fiber assignment: TILEID-tiles.fits, TILEID-targ.fits, TILEID-std.fits, TILEID-gfa.fits, TILEID-sky.fits.
for now, those files leave in the current folders:
https://data.desi.lbl.gov/desi/users/raichoor/fiberassign-sv1/20201212/
https://data.desi.lbl.gov/desi/users/raichoor/fiberassign-sv1/20201216/
https://data.desi.lbl.gov/desi/users/raichoor/fiberassign-sv1/20201218/
where the date corresponds to when I ran the fiber assignment (not related to observation).
I kept files split by creation date to ease the tracking; for instance, the KPNO-generated files where from 20201216/ and 20201218/.

**Comment by moustakas** [comment]
Thanks @araichoor. Yes, I can capture this error easily but I'm thinking about non power-users wanting to get supplemental targeting info and running into this somewhat obscure error. 

Maybe this issue doesn't matter and can be closed but I wouldn't mind @sbailey and/or @djschlegel opining.

**Comment by schlafly** [comment]
Two cents: we have now gone through the effort of having a common $DESI_ROOT/... hierarchy.  We should probably change the leading directories in each case to be something like $DESI_ROOT or drop them.

I don't think we want to give a NERSC file name to something that was actually designed at KPNO.  So the alternative to dropping the leading directories or replacing them with $DESI_ROOT would be to have downstream users deal with it, which also seems okay.

**Comment by sbailey** [comment]
Building on Eddie's suggestion, see [desispec.io.meta.shorten_filename](https://github.com/desihub/desispec/blob/7cb294c0a2175e19a9553f30c76f03a03c0d6b2d/py/desispec/io/meta.py#L420), which substitutes filename prefixes:
  * $DESI_SPECTRO_CALIB/path/to/file -> SPCALIB/path/to/file
  * $DESI_SPECTRO_REDUX/$SPECPROD/path/to/file -> SPECPROD/path/to/file

That could be expanded to also substitute $DESI_ROOT/path/to/file -> DESI_ROOT/path/to/file if it doesn't match one of the more specific substitutions.  The original motivation for `shorten_filename` was to get filenames that fit in a FITS header without needing a CONTINUE, but in principle could be used for cross-site portability using a common $DESI_ROOT/ directory hierarchy.  Or do the equivalent substitution in fiberassign directly.

Note: the header should also record DESI_ROOT so that we can keep track of whether this fiberassign file was run at NERSC or KPNO (even though it isn't supposed to matter...).  For the spectro pipeline Blanc run we remembered to cache DESI_SPECTRO_CALIB in the headers but forgot to cache $DESI_SPECTRO_REDUX/$SPECPROD too ([desispec #1077](https://github.com/desihub/desispec/issues/1077)).  Oops...

**Comment by araichoor** [comment]
ok perfect, very nice suggestions, thanks!

two minor remarks:
- I notice now that, at KPNO, DESI_ROOT=/data/datasystems, whereas I was reading /data; this is because $DESI_ROOT/target is a link to /data/target... I ll update the code for clarity
- because of the 8-characters limit in the header keywords, I plan to use a "DESIROOT" instead of "DESI_ROOT"
that would give in the fiberassign header something like:

DESIROOT = '/global/cfs/cdirs/desi' for NERSC, '/data/datasystems' for KPNO
GFA     = 'DESIROOT/target/catalogs/dr9/0.47.0/gfas' /
SKY     = 'DESIROOT/target/catalogs/dr9/0.47.0/skies' /
SKYSUPP = 'DESIROOT/target/catalogs/gaiadr2/0.47.0/skies-supp' /
TARG    = 'DESIROOT/target/catalogs/dr9/0.47.0/targets/sv1/resolve/bright/' /

would that be ok?

**Comment by araichoor** [comment]
I ve pushed the change to the master branch: https://github.com/desihub/fiberassign/commit/93e1875fb565edc00d549021d7073d47020f0aff

**Comment by sbailey** [comment]
Adding the DESIROOT keyword + prefix substitution looks good.  Please also add links as necessary at KPNO so that you can avoid this special case:
```python
if "desi" in hostname:
     path_to_svn_tiles = "/data/tiles/SVN_tiles"
if "cori" in hostname:
    path_to_svn_tiles = os.path.join(
        os.getenv("DESI_TARGET"), "fiberassign/tiles/trunk"
    )
```
i.e. any time the code is having to do something different for KPNO vs. NERSC, it is probably a sign that we need to be adjusting the directory structure and environment variable setup to make them more similar, instead of special-casing the differences in the code.  That will make it easier to port to other locations too as long as they follow a $DESI_ROOT hierarchy.

**Comment by weaverba137** [comment]
Also, hard-coding 'cori' is not a good idea.

**Comment by araichoor** [comment]
sorry for the late reply; thank you for catching that desi/cori case:
- I 100% agree with you that this should be fixed
- I m not very familiar with link creation, would the executing the following commands at KPNO work:
`mkdir $DESI_TARGET/fiberassign`
`mkdir $DESI_TARGET/fiberassign/tiles/`
`ln -s /data/tiles/SVN_tiles $DESI_TARGET/fiberassign/tiles/trunk`
also, is it ok to do that, knowing that  /data/tiles/SVN_tiles is a svn folder?
- for those two reasons, I would prefer that @geordie666 run such commands at KPNO, as he is the one writing in $DESI_TARGET.

**Comment by geordie666** [comment]
I think I set this up as requested/needed. At NERSC:
```
echo $DESI_TARGET
/global/cfs/cdirs/desi/target

ls $DESI_TARGET/fiberassign/tiles/trunk/
059  060  063  065  066  067  068  070  074  078  080  SV0.html  SV1.html
```
at KPNO:
```
echo $DESI_TARGET
/data/target

ls $DESI_TARGET/fiberassign/tiles/trunk/
059  060  063  065  066  067  068  070  074  078  080  SV0.html  SV1.html
```

**Comment by araichoor** [comment]
thanks a lot @geordie666.
I ve pushed the modified code : https://github.com/desihub/fiberassign/commit/6ed1a606fa685211af445cd0e50f0c161b1d55e9
I ve also replaced a safety check on $HOSTNAME containing cori or desi by a check on the existence of the used environment variables DESI_ROOT, DESI_TARGET, and DESIMODEL.
(and made a commit just after to correct a $DESI_MODEL to $DESIMODEL...)
