### ISSUE TITLE
Add inner buffer around positioner center

### ISSUE THREAD

**Issue by tskisner** [desihub/fiberassign#329]
We should add an inner buffer zone to not consider targets near the positioner center.

**Comment by tskisner** [comment]
Quoting an email from Joe on 4/21/21:

> Regarding Daniel's comment "I wonder if we should be adding an inner boundary for |R1-R2|+buffer" --- Yes, you must do this. Value of buffer should be large enough to admit both the platemaker discrepancy (about 80 um mean) and positioner corrections move (about 35 um RMS). So the 200 um number that Stephen was saying sounds about right to me.
> 
> And as Stephen was saying, we also need to apply a constraint R1+R2-buffer for outer targets.

We already use a 200um buffer when considering targets near the maximum patrol radius, and so it sounds like we should enforce an inner 200um buffer as well.

**Comment by dstndstn** [comment]
Done in 01206c1

**Comment by sbailey** [comment]
Reopening this ticket, since commit 01206c1 implemented this as effectively

    exclude r < max(|R1-R2|, buffer)   #- default buffer=200 um

which is different from Joe's recommendation of

    exclude r < |R1-R2| + buffer

i.e. the buffer is intended to be *in addition to* what we can't reach due to |R1-R2|, not a floor on that.  

He also notes that "We can negotiate on the value for buffer, but it should be additive"; I'm inclined to go with 50 or 100 microns instead of 200 so that we don't make too big a hole.  For comparison, median(| R1-R2 |) = 55 microns, with a long tail that doesn't smell physical (99th percentile 325 um, max 886 um (!)).

**Comment by dstndstn** [comment]
changed to this 6e78851
