### ISSUE TITLE
Record desimeter version in fiberassign-TILEID.fits.gz header

### ISSUE THREAD

**Issue by araichoor** [desihub/fiberassign#363]
While trying to make fba_launch work on my laptop, I noticed that (of course) desimeter is required.
Though, it looks like the desimeter version is not recorded in the fiberassign-TILEID.fits.gz header.

It probably should be added here, right? https://github.com/desihub/fiberassign/blob/1e74f15e039a24ce4747a85363157de190ae2897/py/fiberassign/assign.py#L272-L283

**Comment by sbailey** [comment]
Good catch!  Indeed it is critical that we record the desimeter version.  I had added that to the default dependency checking list in `desiutil.depend.add_dependencies` without realizing that fiberassign was overriding that to a smaller list of packages to check and thus missing desimeter.

Fixed in PR #364.  @araichoor please take a look.
