### ISSUE TITLE
fba_launch ArgumentParser fails on --tiledec -1.

### ISSUE THREAD

**Issue by araichoor** [desihub/fiberassign#409]
The following call fails:
`fba_launch --dtver 1.1.1 --outdir ./ --survey main --program DARK --tileid 999999 --tilera 0 --tiledec -1.`
with:
`fba_launch: error: argument --tiledec: expected one argument`
whereas replacing `--tiledec -1.` by `--tiledec -1.0` works.

This looks like a argparse.ArgumentParser() issue; I do not know if there is a workaround.
I *think* it should not be a problem for the Main survey, as no tile in tiles-main.ecsv has a negative DEC value ending with a dot:

```
>>> d = Table.read("/global/cfs/cdirs/desi/survey/ops/surveyops/trunk/ops/tiles-main.ecsv")
>>> d = d[d["DEC"] < 0]
>>> decs = np.array([dec.split(".")[1] for dec in np.array(d["DEC"]).astype(str)])
>>> (decs == "").sum()
0
```

pinging @schlafly, @sbailey, in case.

**Comment by schlafly** [comment]
I haven't tested this.  But my impression is that if we used the fba_launch --tilera=-1. --tiledec=-2. syntax, this would probably not be an issue.  So my tendency would be to call this working-as-expected in fiberassign, and perhaps open an issue on desisurvey to update fba-main-onthefly.sh to use that invocation syntax.  However, since you've tested that this never actually occurs in practice, I'm only slightly motivated to make a change.  As you say, we force every entry in tiles-*.ecsv to have three digits after the decimal point.

**Comment by araichoor** [comment]
I ve just tested: I confirm that using `--tiledec=-1.` works; so, perfect, no changes to be done on the fiberassign side.
so I ll close this issue.
for the desisurvey side, as https://github.com/desihub/desisurvey/blob/master/bin/fba-main-onthefly.sh is the only script calling fba_launch (right?), no changes are required either.

**Comment by schlafly** [comment]
Yes, that is the only calling script.  But I could add --tilera=$RA there to be consistent here.
