### ISSUE TITLE
Set EBV for all fibers

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#413]
Fiberassign is currently using EBV=0.0 for some targets, apparently including all OBJTYPE='SKY', 'BAD', and '' targets, but also some science targets (OBJTYPE='TGT').  I'm guessing that this is just propagated from input targeting that may be missing EBV columns or have defaults of 0.0, but it would be helpful to catch these cases and use `desiutil.dust.SFDMap` to lookup E(B-V) values.  

This impacts downsteam code that uses the EBV values to interpret extinction for TSNR2 calculations, resulting mis-interpreting these targets as unextincted and thus overexposed.  I'll also file a ticket to catch these on the desispec side, but it would be preferable to have fiberassign output with correct EBV values from the start.

e.g. tile 21311, which in addition to normal SKY and BAD fibers, has a patch of bad imaging:

![image](https://user-images.githubusercontent.com/218471/135024459-b564b744-ae81-46ce-ac2e-ebe4ddc47799.png)

**Comment by djschlegel** [comment]
This happens for all flavors of sky targets (SKY,BAD_SKY,SUPP_SKY) as well as targets that are secondary targets with "OVERRIDE" set to not take the DR9 targeting information.  This should not occur for anything else.

**Comment by araichoor** [comment]
**Foreword:**
The EBV column is not in the columns affected by the patched listed by @dstndstn in [desi-survey 2962].

**TGTs with EBV=0 in fiberassign-TILEID.fits.gz files:**
A complementary way to say this: those are either stand-alone secondaries or ToOs.
Because EBV, which is not in the ledgers, neither is in the static desitarget catalogs for secondaries (and there is no static catalogs for ToOs); so that EBV information just does not exist in desitarget catalogs for those targets.

Below a code snippet assessing that TGTs with EBV=0 are either stand-alone secondaries or ToOs.

```
# gather TARGETIDs from stand-alone secondaries and ToOs
>>> fns = ["/global/cfs/cdirs/desi/survey/ops/surveyops/trunk/mtl/main/ToO/ToO.ecsv"]
>>> fns += sorted(glob("/global/cfs/cdirs/desi/target/catalogs/dr9/1.1.1/targets/*/secondary/*/*targets-*-secondary.fits"))
>>> tids = []
>>> for fn in fns:
>>>     tids += list(Table.read(fn)["TARGETID"])
# main fiberassign files:
>>> subdirs = ["001", "002", "003", "004", "008", "020", "021", "022", "023", "024", "025", "026"]
>>> fafns = []
>>> for subdir in subdirs:
>>>     fafns += sorted(glob("/global/cfs/cdirs/desi/target/fiberassign/tiles/trunk/"+subdir+"/fiberassign-??????.fits.gz"))
# stacking fiberassign files:
>>> d = vstack([Table(fitsio.read(fafn, columns=["TARGETID", "OBJTYPE", "EBV"], ext="FIBERASSIGN")) for fafn in fafns])
# number of TGTs with EBV=0
>>> ((d["EBV"] == 0) & (d["OBJTYPE"] == "TGT")).sum()
79210
# number of TGTs with EBV=0 and not in tids:
>>> ((d["EBV"] == 0) & (d["OBJTYPE"] == "TGT") & (~np.in1d(d["TARGETID"], tids))).sum()
0
```

Note that for secondaries, information (flux columns only) from static catalogs is only propagated to fiberassign files since PR https://github.com/desihub/fiberassign/pull/404.

Lastly, I ve checked that all targets in ```$DESI_TARGET/catalogs/dr9/1.1.1/targets/main/resolve/{program}/targets-{program}-hp-*.fits``` have EBV>0.

**Fix:**
I see two possible approaches:
- approach (a): the intermediate TILEID-{sky,skysupp,scnd,too}.fits currently don t have an EBV column (hence filled with zeros in fiberassign-TILEID.fits.gz) => we could add EBV for each of those files, and that will propagate in fba-TILEID.fits and fiberassign-TILEID.fits.gz; but stuck and unassigned fibers would still have EBV=0;
- approach (b): once the fiberassign-TILEID.fits.gz is created, read it and populate the EBV=0 rows with correct EBV values.
The second approach sounds simpler (and probably faster as the dust maps should just be queried once); also, it will populate the EBV=0 values from the stuck sky or unassigned fibers; I d favor that second approach.

**Comment by geordie666** [comment]
If needed, I could also add E(B-V) to the ToO ledger. Just let me know.

**Comment by sbailey** [comment]
Let's not do option (b) because (if I understand correctly) it involves writing a file, and then reading it back in, updating it, and writing it back out under the same name, raising the possibility that you don't know which version of the file is really there.  We could use a different intermediate file name, but that still seems awkward just to update a column.

I was hoping for something like approach (c): just before writing the final file, identify any EBV=0 targets and use `desiutil.dust` to correct them with non-zero values.

I don't think we need to require the input files to have EBV (since for stuck positioners we're inventing targets anyway and want to be able to set their EBV too), and we shouldn't have to round-trip any files to disk just to update some default values.

**Comment by araichoor** [comment]
First: note that in fba_launch, I already re-open fiberassign-TILEID.fits.gz after it has been written, to add some informations in the header:
https://github.com/desihub/fiberassign/blob/33c15ad9904091d185e6329a7f6f6e2575e81ed1/bin/fba_launch#L372-L386

But it looks like I could actually populate the EBV=0 rows with correct values in the outdata array, just before it is written in the FIBERASSIGN extension: 
https://github.com/desihub/fiberassign/blob/33c15ad9904091d185e6329a7f6f6e2575e81ed1/py/fiberassign/assign.py#L1349-L1353
I ll test that.

**Comment by araichoor** [comment]
I ve made a PR for that: https://github.com/desihub/fiberassign/pull/414.
We can continue there the discussion on how to implement that.

**Comment by araichoor** [comment]
Addressed in merged PR https://github.com/desihub/fiberassign/pull/414.
Closing.
