### ISSUE TITLE
Output row index in input target list

### ISSUE THREAD

**Issue by apcooper** [desihub/fiberassign#51]
It would be useful to store, in the tilemap output, the row number of the assigned and potential targets in the input MTL file. That would make it very quick to make a table listing the assigned tile and actual/potential fibre for each target in the input row order, without matching (see `reduce_fiber_maps_to_mtl` [here](https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/fiberassign.py#L355)).  I think the input row index for each target is available in the data structures that are being used to construct the tile maps, so it seems better to store that than have to reconstruct it by matching on TARGETID. 

Perhaps the row number could be written as a second column in HDU2 alongside the POTENTIALTARGETID list, since that list contains both the assigned and potential targets for each fiber.

**Comment by tskisner** [comment]
Hello @apcooper , much has changed in the code since this issue was opened.  The current output file format is a FITS file per tile, and there is an HDU ("TARGETS") which contains a full copy of all columns of the input target catalog (so there is no need to index back to the original catalog).  In the case that different input catalogs have different column names, the code forms the superset of input columns and fills just the columns of the catalog from which each target came.  I will close this issue now, but please reopen it if I misunderstood the intention of the ticket.
