### ISSUE TITLE
Priorities for standard stars

### ISSUE THREAD

**Issue by apcooper** [desihub/fiberassign#78]
Linked to https://github.com/desihub/desitarget/issues/205

STD_WD should have priority over STD_FSTAR (and other types of standard if we add more), but there is no concept of priority for standards in the current code. This probably needs to be implemented in desitarget *and* fiberassign.

**Comment by sbailey** [comment]
The WD density is low enough that for the purposes of fiberassignment they could be treated as normal targets with priority higher than QSOs regardless of their observing state, thus guaranteeing their placement.  That would require updating their entries in desitarget/data/targetmask.yaml but not any code changes in either desitarget or fiberassign.

That might be slightly controversial since it would imply WDs bumping other science targets, where for regular standards we only bump science targets if absolutely necessary to achieve a minimum density of calibrators.

Broader than just WDs, it would still be useful to have the concept of standard star priorities within fiberassignment, e.g. to prioritize solid standards close to the desired color locus while falling back to a lower priority set of broader color cut standards only if needed.

**Comment by sbailey** [comment]
Let's use the SUBPRIORITY column for ranking the order in which standard stars are assigned, just like it is used for science targets.  Upstream we'll work on making the SUBPRIORITY for standard stars a meaningful ranking.

Note: fiberassign should not crash (or have undefined order results) if some (or all) subpriorities are the same.

**Comment by sbailey** [comment]
Discussions on other email threads and tickets has come to the conclusion that using SUBPRIORITY to rank standard stars is a bad idea, e.g. because standards overlap with MWS targets and ranking them by their usefulness as standards conflicts with making them truly random as science targets.

Current thinking is to make WD high-priority low-density normal targets so that they will always get placed, and then treat other standards as the same.  This still needs to be done in a reproducible way and thus may still use SUBPRIORITY, but the the SUBPRIORITY shouldn't be ranked in a special way.

**Comment by moustakas** [comment]
It was discussed and decided here and in https://github.com/desihub/desitarget/issues/337 that standard stars would not be rank-ordered, in order to not create issues with the selection and priorities of MWS science targets.
