### ISSUE TITLE
Sky Camera positions

### ISSUE THREAD

**Issue by forero** [desihub/fiberassign#95]
There will be 20 positioners on the periphery of the 5000 fibers. Their purpose is measuring sky background and must be then assigned to blank sky positions. `fiberassign` must also find and report these sky location for every tile.

**Comment by sbailey** [comment]
The locations of these positioners are in `$DESIMODEL/data/focalplane/fiberpos-all.fits` where `DEVICE_TYPE=='ETC'` (ETC=Exposure Time Calculator since that is what these positioners are used for).  Currently `desimodel.io.load_fiberpos()` only returns the 5000 normal positioner locations, but it could be extended with an option to read this file instead and return the locations of the requested positioner type.  Definitions coming from [DESI-0530](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=530):
* POS = normal positioners, which could be assigned to science, sky, or stdstars
* ETC = Exposure Time Calculator sky fiber positioners
* FIF = Fiber Illuminated Fiducials
* GIF = GFA Illuminated Fiducials
* OPT = location of a hold but potentially nothing in it
* NON = defined location, but no hole or device there (!)

**Comment by forero** [comment]
Solved by #119
